# Generated by Django 6.0.2 on 2026-02-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('beadle', 'Beadle'), ('prof', 'Professor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(choices=[('he/him', 'he/him'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('he/they', 'he/they'), ('she/they', 'she/they'), ('other', 'other'), ('none', 'none')], max_length=20),
        ),
    ]
