# Generated by Django 6.0.2 on 2026-02-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_role_alter_profile_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
    ]
