# Generated by Django 5.2.1 on 2026-04-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.courseuser'),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='courses.course'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.attendancesession'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('course', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'course_user')},
        ),
    ]
