# Generated by Django 6.0.2 on 2026-02-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
