# Generated by Django 5.1.6 on 2026-04-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='layout_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('compact', 'Compact'), ('exam', 'Exam'), ('custom', 'Custom')], default='lecture', max_length=50),
        ),
    ]
