# Generated by Django 5.1.6 on 2026-04-17 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_layout_course_layout_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='layout_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('compact', 'Compact'), ('exam', 'Exam'), ('donut', 'Donut'), ('custom', 'Custom')], default='lecture', max_length=50),
        ),
    ]
