# Generated by Django 5.1.6 on 2026-04-17 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_layout_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('layout', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='layout_type',
        ),
        migrations.AddField(
            model_name='course',
            name='layout_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.layouttemplate'),
        ),
    ]
