# Generated by Django 5.1.6 on 2026-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_layouttemplate_remove_course_layout_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='layout_template',
        ),
        migrations.AddField(
            model_name='course',
            name='layout_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('compact', 'Compact'), ('exam', 'Exam'), ('donut', 'Donut'), ('custom', 'Custom')], default='lecture', max_length=50),
        ),
        migrations.DeleteModel(
            name='LayoutTemplate',
        ),
    ]
