# Generated by Django 5.2.1 on 2026-04-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_plan', to='courses.course')),
                ('course_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='courses.courseuser')),
            ],
            options={
                'verbose_name': 'seat_plan',
                'verbose_name_plural': 'seat_plans',
                'ordering': ['course'],
            },
        ),
    ]
