# Generated by Django 5.2.1 on 2026-04-17 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseuser')),
            ],
            options={
                'unique_together': {('course', 'row', 'col'), ('course_user',)},
            },
        ),
    ]
