# Generated by Django 5.1.6 on 2026-04-16 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('seat_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('course_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courseuser')),
            ],
            options={
                'unique_together': {('course', 'row', 'col')},
            },
        ),
        migrations.DeleteModel(
            name='SeatPlan',
        ),
    ]
