# Generated by Django 5.1.6 on 2026-04-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('seat_plan', '0002_seatassignment_delete_seatplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('course', 'row', 'col')},
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='col',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seatassignment',
            name='row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seatassignment',
            unique_together={('course', 'row', 'col'), ('course_user',)},
        ),
    ]
